### ISSUE TITLE
Module was compiled with an incompatible version of Kotlin

### ISSUE THREAD

**Issue by Str4tos** [SuperAwesomeLTD/sa-mobile-sdk-android#92]
Hello.
SuperAwesome 8.1.2 migrate to early version of Kotlin 1.5.0.
We are not yet ready to use 1.5.0 and get an error during build:
```
superawesome-base-8.1.2-api.jar!/META-INF/superawesome-base_release.kotlin_module: 
Module was compiled with an incompatible version of Kotlin. 
The binary version of its metadata is 1.5.1, expected version is 1.1.16.
```
Please go back to Kotlin version 1.3.72 for increase version compatibility.

Thanks!

**Comment by dnharjani-sa** [comment]
Hey Str4tos. 

Unfortunately due to our strict compliance and security protocols we need to update our libraries to the latest versions unless there are specific reasons for downgrading. Since 1.3.7 is a year old now I don't believe we can downgrade that library. We are looking into bundling the version of Kotlin with the library in order to prevent issues like this. 

In the mean time we recommend upgrading your version of Kotlin if possible. If you are not able
